### ISSUE TITLE
Feature request - Ability to access all rift gates and shrines at Normal, Veteran, Elite and Ultimate levels

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#10]
Would like ability to enable (and clear) rift gates within each act and at each level in GD if possible.
e.g Rgate U all - for all Acts in Ultimate
     Rgate U clear to uncheck all riftgate access
     Rgate U Act <gate name>

Would like to ability to enable (and clear) shrines within each location and in each level in GD if possible.
e.g. Shrine U all
       Shrine U clear
      Shrine U Act  <shrine name) - not sure shrines have names

**Comment by Odie** [comment]
With shrines... you can take a look at the data by doing "show shrines". There is a bunch of 16 byte array there. Probably, each entry corresponds to every shrine unlocked. I haven't been able to figure out where in the DB these these 16 byte values might be coming from though.

I suppose it's possible to hard code those values directly into the editor, though that's less preferable.

With portals... I don't even know where that info is being recorded. x)

**Comment by GrimDawn-max** [comment]
Yes I see the same data for shrines. The odd thing there is that the numbers don't match with the published no. of shrines per difficulty. In Normal there are 47, in Elite 51 and Ultimate is 57. 
Hopefully you can do a query or db table lookup. If this request were to necessitate hard coding don't implement it. I don't want you to trash your utility because of my request, just close it out as a not possible. I can always use the other utilities if I really want to fiddle with gates and shrines. 

Riftgates I think are similar, in an array. When I did a "find riftgates" it gave me a list of quest related items but nothing else.  GDStash and GDDefiler both have the two options (see screenshots). I wonder how they have done it. 

<img width="1116" alt="RGGDS" src="https://user-images.githubusercontent.com/64788480/81501310-bc062580-92a5-11ea-9499-93d45802df32.png">

<img width="791" alt="RGGDDef" src="https://user-images.githubusercontent.com/64788480/81501318-c3c5ca00-92a5-11ea-84fb-27ebba4418d2.png">

**Comment by Odie** [comment]
So, both rift gates and shrines are now available as of version 0e3ba7a824fb674133468444d5788538cb66d967.

A bit more details about how to list and set/activate rift gates can be found here:
https://forums.crateentertainment.com/t/tool-gd-save-file-editor/35817/1025

What I didn't mention in the post is that the editor also knows how to work with shrine IDs as well.
You can show all shrines by doing:
```
shrine list
```

Adding activated shrines works like so:
```
set shrines/0 "Ancient Grove"
```

Or you can just do:
```
set shrines/0 all
```

I'm not entirely sure if this is useful at all, since doing this won't give you any of the rewards attached to their activation. The editor won't even give you devotion points for them at the moment.

**Comment by GrimDawn-max** [comment]
Hi Odie,

I did see the update in forum first and was going to ask about shrines ;-). You could always set devotion points in the editor but these would be out of sync with the shrines actually activated. Having the ability to manage shrines as well as devotion points makes things more balanced IMHO. 
I'll do some testing but if you want to go ahead and close the request please do so. If I find something I can always send a note back. And thanks once again for another great addition to the tool set !

**Comment by Odie** [comment]
Alrighty!

Lemme know if you think something more needs to be added. The commands “shrine” and “gate” don’t do very much yet but can be changed to update the character in a slightly more complex way. :)
