### ISSUE TITLE
Feature request - Delete function in editor

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#3]
Would like to request a delete function in editor. Workflow would allow either a single or a bulk (batch) delete of items in inventory, stash, shared stashes. As per conversations workflow that probably makes most sense:

Generate a bunch of items into mod transfer stash
Review exact stats in game
Pick and move the items you want into a separate stash bag/tab.
Batch delete the rest of the items
Batch copy move items from mod stash to vanilla stash

A similar workflow should work fine with vanilla stash also. Generate a bunch of items into vanilla stash
Review
Pick
Batch delete junk

"If you stick to the vanilla stash (though it is smaller), then all you’d need is a batch delete command. I can also throw in a batch create command so you can keep batch file editing to a minimum (if needed at all)."

**Comment by Odie** [comment]
This was *just* added in efb3ab9b965658a26edc491230feb92fc13a8032 and has been released!
Let me know if something breaks! =)
