### ISSUE TITLE
Feature request - add ability for editor to create items at different levels

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#5]
When creating items editor will create items at highest level. If a level 84 and level 94 item with same name exists, it seems it will only create a level 94 item (have not tested this completely). This is not an issue but it would be nice to have the ability to tell editor to create an item at a lower level

**Comment by Odie** [comment]
This is supported.
```
set <field path to inventory items collection> <item name> <optional item-level-cap>
```

The editor now defaults to creating the highest level item available in the game. Unless you place a limit on it. It used to be that the item creation always created something that is at or below your the loaded character's level. However, many users were left scratching their heads when they tried to create an item above their character level, and all the edtior told them was "Sorry, the item could not be created."

I guess a more descriptive message would have helped. But I just opted to make it create the highest level item instead, so the creation always succeeds if the item name is something valid.

Please do take a look at https://odie.github.io/gd-edit-docs/commands/. Readings the docs is never fun, but you may find something useful in there. =)
