### ISSUE TITLE
Feature request - Add character delete function

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#7]
At the moment removing an entire character (vanilla or mod) is a manual process of deleting the file in the save directory of the game. If possible it would be great to have a delete character function from within the editor. Potential work flow would be

Start editor
Review character list
Select character to delete
Run character delete command
Ask for confirmation to delete
Remove character file (either delete and/or move file out of save folder, otherwise it will still show in menu)

**Comment by Odie** [comment]
Added in 05c8d8a87d89b897ecec110a13721d7662dacdc0. Release pushed.

A `delete` command has been added. 
There are 3 variants:
```
> delete
> delete <character-name>
> delete <full-path-to-gdc-file>
```
(The load command has also been updated to work in the same way.)

In all cases, the editor will move the folder for the character to the recycle bin. This makes restoring pretty straight forward. This way, the editor doesn't have to deal with managing some kind of deleted characters folder. There are also no additional commands to learn to manage that history.

Note that this particular feature required some reworking of the code that monitors the transfer stash. Hopefully, everything will continue to function correctly. =)

**Comment by GrimDawn-max** [comment]
Hi Odie,

Tested delete function on vanilla and mod characters. Command delete the character and moved file to the recycle bin as expected. Was also able to restore character. Also tested the set, batch and remove functions for transfer stash of mod character. All worked without an issue. You can go ahead and close this request. Thanks once again !

**Comment by Odie** [comment]
Great! =)
