### ISSUE TITLE
Feature request - Add option to copy a character as a mod character 

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#8]
Currently able to create new, vanilla characters using write <character name> command.
This does work so well if the character is to be used in a mod, as the character is created in the game save file by default, rather than the mod game file. Moving the file into the mod save directory manually works but it seems to create a duplicate in the vanilla save directory if done this way.

Would like option to copy a character with a "mod" flag - as is done in GDStash, along with creating the mod character file in the correct mod character save location only, preventing character duplication occurring in vanilla save file location.

**Comment by GrimDawn-max** [comment]
Found this info on mod & vanilla character behaviour - https://forums.crateentertainment.com/t/mod-hairstylist-a-barber-in-town/51152/39
"kinda, as far as I can tell, the game determines where to save the char based on the mod-flag. If it is not set, the char is saved in main. If it is set, the char is saved in the user dir.
This is independent of where the char was loaded from (main or user).

If you play a mod, the char will always be loaded from user, if you play vanilla, it will always be loaded from main however.

So if you copy the main char to user, the mod will load the user char, but update the main char.
When you exit the game and then play the mod again, it will load the unchanged user char (while your progress was saved in main), so all the progress you made playing the mod last time will be ‘lost’, as that progress is not stored in the file that is being loaded."

Note: If I delete the character from main it will no longer show in vanilla and only update the mod is user folder

**Comment by GrimDawn-max** [comment]
One last thing - I was incorrect in how GDS works with the mod flag. It seems it creates a character file in both main and user. I then delete the one out of main to keep the mod character.

**Comment by Odie** [comment]
Hmm! This is a rather fascinating request.

---
About the tech aspect of things...
1. Mod -> Vanilla character
It's cool that GDS is doing it. If it's as simple as flipping a flag, that'd totally be doable.

2. Vanilla -> Mod character
This might be a little bit harder. As mentioned in another message somewhere, the game keeps *some* record of which mod and which map you've created the character with. It looks like this might be hiding in "levels_world001.map/Normal/map.dat" in the character directory. The file seem to list both the map and the mod the character was created with. There are also other more cryptic items like "map version" and "spawn coordinates".

It does look like the file looks mostly the same for a mod that changes relatively little about the main game. So it can still conceivably be done...

So I suppose with some experimentation, this might possibly work. But beyond this "how", I want to understand a bit about the "why" behind this.

---

What is the purpose of trying to copy characters back and forth between mods?  

For mods that are pretty light on modifying the game, like UI-X, isn't playing with the mod permanently on, just fine? Why would someone want to copy this character over to the vanilla game? What happens to the extra items in the enlarged stashes?

For mods that heavily change the game, like the Diablo 2 mod, is there a purpose to bringing the character over? If most of the skills and items will be removed altogether?

I'm having difficulty understanding the motivation behind this feature request.

**Comment by GrimDawn-max** [comment]
No need to copy characters back and forth for me. Just character from vanilla -> mod (so option 1 only). Not sure why anyone would want to go the other way either, that was just in the thread I found. Ditch option 2 altogether.

The "Why" and my primary motivation ? I'm lazy :-) gd-edit only creates a character in main (vanilla). In GDS it creates it in both main and user when you select the In mod box. If I then delete the character out of main I'm left with just the "mod" character. The game is then forced to write just to the mod character. If gd-edit can create the character in the correct directory based on what it is (vanilLa or mod) that would be awesome cause then I don't have to move things around. 

I compared a vanilla and a mod character and all fields there are the same but this was a compare of a character and a copy of that character, so the fields wouldn't be different. I can create a fresh mod character at level 1 and compare it's player.gdc file, but I suspect I won't see a difference. As you said the difference must be elsewhere. The levels directory sounds promising !

**Comment by Odie** [comment]
Well, I've added this in 5890c33e55a3250d3335d45010c29dbbccb07c49. A release has been pushed.

You can now explicitly ask for a character to be saved as a mod character, like so:
```
> write OdieModded mod
```

Specifically, add the string "mod" to the end of the "make a copy of this character" command.

I tested briefly with UI-X, it seems to work okay. Give it a go and see if it works for you.

**Comment by GrimDawn-max** [comment]
Works as expected. I can create a mod only character and it creates the character in the mod (user) folder without a duplicate. Thanks once again for another handy edition to the editor Odie ! Go ahead and close out if there is nothing else left to do on this one for you.
