### ISSUE TITLE
Feature request - Display "Hidden" field on items 

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#9]
It appears Crate has implemented hidden attributes on items in-game. These can't be seen so players are unaware of them. The GT site does show the hidden properties on at least 17 items. It can therefore be displayed. Refer to e-mail thread for more details on items and where this property may be within the dbr files.

It would be great if this hidden property can be displayed (perhaps in bold flashing RED italics or something so it's obvious)) as part of the output description generated when creating an item.

**Comment by Odie** [comment]
Added by 7778d4cc020f793cd802d244ad147ae1674358f1.

New version has been released. =)

**Comment by GrimDawn-max** [comment]
Hi Odie - I'm running the latest update (it tells me this when I tried the update command) but I do not see the field highlighted in red (I'm not colour blind so RGB is not an issue for me). Here is a screenshot of what I get. 
<img width="463" alt="HiddenNoRed" src="https://user-images.githubusercontent.com/64788480/81227605-aa2d3580-8fba-11ea-8e9c-ddb9c3affa88.png">

My version is gd-edit 0.2.0-SNAPSHOT [build 08f70f3] atm.

**Comment by Odie** [comment]
Oh, my bad! The publish script I was using did not complete and actually push out that update. X_X

It should be working now.

**Comment by GrimDawn-max** [comment]
It is working with the red highlight now. 
You really should mention that in the editor thread. No other tool has this reveal capability ! I'm tempted to mention it in the Hidden properties thread there, but I'll leave that up to you. This is all great stuff IMHO and thanks once again !

**Comment by Odie** [comment]
Well, glad you like it. :)

Feel free to post things wherever you like. I’m not really active on the forums besides the gd-edit thread, anyway.
